version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    ports:
      - 4170:4170
      - 4171:4171
    restart: always
    command: /nsqlookupd
    
  nsqd:
    image: nsqio/nsq
    ports:
      - 4150:4150
      - 4151:4151
    restart: always
    command: /nsqd

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
